services:
  app:
    build: .
    container_name: siroko-cart-api
    ports:
      - "8000:8000"  # Exposing application port 8000
    volumes:
      - .:/var/www/html  # Mapping the local directory to match Dockerfile WORKDIR
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/var/data.db  # Path where the SQLite database file is stored
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
