controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

cart_controllers:
    resource:
        path: ../src/Cart/Infrastructure/Controller/
        namespace: App\Cart\Infrastructure\Controller
    type: attribute
